/**
 * ~~~ THE SIGILS EACH HOUND WEARS ~~~
 *
 * Arr, every base-dog be branded with a sigil -- an icon that marks
 * its nature in the UI. These glyphs be the last defence against
 * the void's formlessness, giving each hound a face that mortals
 * can recognize. Without them, all would blur into the nameless dark.
 *
 * Carrion hordes trill their profane accord with eldritch plans --
 * but at least they wear distinct sigils while doing so.
 */

/** Central registry mapping class names to their display sigils */
const BASE_DOG_ICONS: Record<string, string> = {
    TalkingDog: '\uD83D\uDCAC',
    RandomRecipesRetriever: '\uD83C\uDF73',
    CountryFlagBlackLab: '\uD83C\uDF0D',
    DishFlagBlackLab: '\uD83C\uDF7D\uFE0F',
    RandomEveryThingRetriever: '\uD83C\uDFB2',
    QueryRetriever: '\uD83D\uDD0D',
    BodyRetriever: '\uD83D\uDCE6',
    WarframeAlertsRetriever: '\uD83C\uDFAE',
    BloodhoundRouteRetriever: '\uD83D\uDDFA\uFE0F',
    BloodhoundIsochroneRetriever: '\u23F1\uFE0F',
    OsmLandmarksRetriever: '\uD83C\uDFDB\uFE0F',
    OsmTracksRetriever: '\uD83E\uDD7E',
    OsmVegetationRetriever: '\uD83C\uDF33',
    OsmFastRoadsRetriever: '\uD83D\uDEE3\uFE0F',
    HueBridgeEnvRetriever: '\uD83D\uDD10',
    HuePlaygroundRetriever: '\uD83D\uDCA1',
    PublicTransportRetriever: '\uD83D\uDE8C',
    WeatherRetriever: '\u26C5',
    AirQualityRetriever: '\uD83C\uDF2B\uFE0F',
    GeocodingRetriever: '\uD83D\uDCCD',
    WikiNearbyRetriever: '\uD83D\uDCDA',
    SunRetriever: '\u2600\uFE0F',
    SpeciesRetriever: '\uD83E\uDD8E',
    BirdRetriever: '\uD83E\uDD86',
    PhenologyRetriever: '\uD83C\uDF38',
    WebcamRetriever: '\uD83D\uDCF7',
    RegionalNewsRetriever: '\uD83D\uDCF0',
    TransitTripRetriever: '\uD83D\uDE82',
    ElevationRetriever: '\u26F0\uFE0F',
    TrailRetriever: '\uD83E\uDDB6',
    ParkingRetriever: '\uD83C\uDD7F\uFE0F',
    PlaygroundRetriever: '\uD83C\uDFA0',
    DrinkingWaterRetriever: '\uD83D\uDEB0',
    ChargingStationRetriever: '\u26A1',
    NoiseRetriever: '\uD83D\uDD07',
    OpenFoodRetriever: '\uD83C\uDF54',
    AstronomyRetriever: '\uD83C\uDF19',
    WaterRetriever: '\uD83C\uDF0A',
    HistoricalWeatherRetriever: '\uD83D\uDCC5',
    CurrencyRetriever: '\uD83D\uDCB1',
    HolidayRetriever: '\uD83C\uDF89',
    WikiSearchRetriever: '\uD83D\uDD0E',
    SeasonRetriever: '\uD83C\uDF43',
    IPGeoRetriever: '\uD83C\uDF10',
    RandomFactRetriever: '\uD83E\uDD14',
    SpaceRetriever: '\uD83D\uDE80',
    OpenLibraryRetriever: '\uD83D\uDCDA',
    GitHubTrendingRetriever: '\uD83D\uDC19',
    JsonStorageRetriever: '\uD83D\uDCBE',
    JokeRetriever: '\uD83D\uDE02',
    DadJokeRetriever: '\uD83E\uDD26',
    ChuckNorrisRetriever: '\uD83E\uDD4B',
    CatFactRetriever: '\uD83D\uDC31',
    FoxRetriever: '\uD83E\uDD8A',
    DuckRetriever: '\uD83E\uDD86',
    DictionaryRetriever: '\uD83D\uDCD6',
    DatamuseRetriever: '\uD83D\uDD24',
    QuoteRetriever: '\uD83D\uDCAC',
    GutenbergRetriever: '\uD83D\uDCDA',
    WikidataRetriever: '\uD83E\uDDE0',
    StarWarsRetriever: '\u2B50',
    RickMortyRetriever: '\uD83D\uDEF8',
    HarryPotterRetriever: '\uD83E\uDE84',
    GhibliRetriever: '\uD83C\uDFAC',
    MusicBrainzRetriever: '\uD83C\uDFB5',
    LyricsRetriever: '\uD83C\uDFA4',
    RadioBrowserRetriever: '\uD83D\uDCFB',
    F1Retriever: '\uD83C\uDFCE\uFE0F',
    SportsDBRetriever: '\uD83C\uDFC6',
    ChessRetriever: '\u265F\uFE0F',
    NpmRetriever: '\uD83E\uDDF1',
    StackExchangeRetriever: '\u2753',
    GitHubPublicRetriever: '\uD83D\uDEE0\uFE0F',
    AirportRetriever: '\uD83D\uDEEB',
    GeoNamesRetriever: '\uD83C\uDFD9\uFE0F',
    WikivoyageRetriever: '\uD83E\uDDF3',
    TriviaRetriever: '\uD83C\uDFAF',
    BoredRetriever: '\uD83E\uDD71',
    RandomUserRetriever: '\uD83D\uDC64',
    BibleRetriever: '\u271D\uFE0F',
    QuranRetriever: '\u262A\uFE0F',
    DiseaseRetriever: '\uD83E\uDDA0',
    OpenFdaRetriever: '\uD83D\uDC8A',
    CocktailRetriever: '\uD83C\uDF79',
    MealRetriever: '\uD83C\uDF7D\uFE0F',
    WaybackRetriever: '\u23F3',
    DogCeoRetriever: '\uD83D\uDC15',
    PicsumRetriever: '\uD83D\uDDBC\uFE0F',
    NasaApodRetriever: '\uD83C\uDF0C',
    AgifyRetriever: '\uD83D\uDC76',
    NationalizeRetriever: '\uD83C\uDFF3\uFE0F',
    GenderizeRetriever: '\u26A7\uFE0F',
    PokeApiRetriever: '\uD83C\uDFAE',
    DeckOfCardsRetriever: '\uD83C\uDCCF',
    ScryfallRetriever: '\uD83C\uDFB4',
    LibreTranslateRetriever: '\uD83D\uDDE3\uFE0F',
    TvMazeRetriever: '\uD83D\uDCFA',
    HackerNewsRetriever: '\uD83D\uDD36',
    LemmyRetriever: '\uD83C\uDF31',
    CoinGeckoRetriever: '\uD83E\uDD8E',
};

/** Look up a hound's sigil by its class name -- returns undefined if the hound be unmarked */
export function getBaseDogIcon(className: string): string | undefined {
    return BASE_DOG_ICONS[className];
}
