/**
 * Auto-generated by scripts/inject-ui-api-base.cjs — nicht manuell bearbeiten.
 * Quelle: PUBLIC_API_BASE_URL in Repo-Root-.env (siehe .env.example).
 * Leer lassen für Same-Origin im Browser (SPA und API unter derselben Origin).
 *
 * API_PREFER_DELIVERY_ORIGIN: bei integration/production-Build gesetzt — unabhängig von Angular isDevMode(),
 * damit absolute Links auf Staging/Prod nicht fälschlich localhost nutzen.
 */
export const API_PREFER_DELIVERY_ORIGIN = false;
export const API_ORIGIN_INJECTED = "http://localhost:3000";
