/**
 * Auto-generated by scripts/inject-ui-api-base.cjs — do not edit by hand.
 * Source: PUBLIC_API_BASE_URL in repo root .env (see .env.example).
 * Empty string means same origin in the browser (SPA and API on the same origin).
 *
 * API_PREFER_DELIVERY_ORIGIN: set for integration/production builds so absolute links
 * on staging/prod do not fall back to localhost unless intended.
 */
export const API_PREFER_DELIVERY_ORIGIN = false;
export const API_ORIGIN_INJECTED = "http://localhost:3000";
